# Generated by Django 2.0.2 on 2019-07-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remalle', models.TextField(blank=True, null=True, verbose_name='Remalle')),
                ('recta', models.TextField(blank=True, null=True, verbose_name='Recta')),
                ('recubridora', models.TextField(blank=True, null=True, verbose_name='Recubridora')),
                ('collaretera', models.TextField(blank=True, null=True, verbose_name='Collaretera')),
                ('elastiquera', models.TextField(blank=True, null=True, verbose_name='Elastiquera')),
                ('boton_ojal', models.TextField(blank=True, null=True, verbose_name='Botón y ojal')),
                ('otros', models.TextField(blank=True, null=True, verbose_name='Otros')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Confección',
                'verbose_name_plural': 'confecciones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla_mesa', models.TextField(verbose_name='Tallas en mesa')),
                ('estampado', models.TextField(max_length=200, verbose_name='Estampados')),
                ('bordado', models.TextField(max_length=200, verbose_name='Bordados')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Corte',
                'verbose_name_plural': 'Cortes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Disenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del diseño')),
                ('imagen', models.ImageField(upload_to='producción', verbose_name='Imagen del diseño')),
                ('tallas', models.IntegerField(verbose_name='Tallas del diseño')),
                ('codigo_disenio', models.CharField(max_length=200, verbose_name='Código de diseño')),
                ('observacion', models.CharField(blank=True, max_length=400, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Diseño',
                'verbose_name_plural': 'Diseños',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(verbose_name='Talla')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('observaciones', models.CharField(blank=True, max_length=400, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.Disenio', verbose_name='Código de diseño')),
            ],
            options={
                'verbose_name': 'Planeación',
                'verbose_name_plural': 'Planeaciones',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='corte',
            name='nombre_disenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.Disenio', verbose_name='Nombre del diseño'),
        ),
        migrations.AddField(
            model_name='corte',
            name='nombre_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.InventarioInsumos', verbose_name='Nombre de insumo'),
        ),
        migrations.AddField(
            model_name='confeccion',
            name='nombre_disenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.Disenio', verbose_name='Nombre del diseño'),
        ),
    ]
