# Generated by Django 2.0.2 on 2019-07-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=200, verbose_name='Nombre del insumo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de compra')),
                ('observacion', models.CharField(blank=True, max_length=400, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Inventario de Insumo',
                'verbose_name_plural': 'Inventario de Insumos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InventarioInsumosBasicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=200, verbose_name='Nombre del insumo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de compra')),
                ('observacion', models.CharField(blank=True, max_length=400, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Inventario de Insumo Básico',
                'verbose_name_plural': 'Inventario de Insumos Básicos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('ruc', models.CharField(max_length=200, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=400, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='inventarioinsumosbasicos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.Proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='inventarioinsumos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.Proveedor', verbose_name='Proveedor'),
        ),
    ]
