# Generated by Django 2.0.2 on 2019-07-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=200, verbose_name='Placa')),
                ('color', models.CharField(max_length=200, verbose_name='Color')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=200, verbose_name='Nombre de tienda')),
                ('direccion', models.CharField(max_length=400, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribucion.Carro', verbose_name='Carro')),
                ('disenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.Disenio', verbose_name='Producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribucion.Tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['-fecha'],
            },
        ),
    ]
